---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    wego.weave.works/app-identifier: wego-84764e7a2950e1c2a3ed8e063db3f840
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  config_url: ssh://git@github.com/dcherubi/gitops-test.git
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/dcherubi/podinfo-deploy.git
